### ISSUE TITLE
Comprar materiales

### ISSUE THREAD

**Issue by David-Estevez** [asrob-uc3m/air-hockey#2]
Comprar materiales para air-hockey:

* [x] Electrónica de impresora 3D
* [x] Cosas de RS (RasPi, Tarjetas SD, Webcams...)
* [x] Mesa Air Hockey

**Comment by David-Estevez** [comment]
Electrónica de impresora 3D comprada y enviada, falta recibirla.

**Comment by KFRodicio** [comment]
La mesa de air-hockey se comprará mañana, salvo problemas

El 16/5/2017 6:23 p. m., "David Estévez Fernández" <notifications@github.com>
escribió:

Electrónica de impresora 3D comprada y enviada, falta recibirla.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/asrob-uc3m/air-hockey/issues/2#issuecomment-301836505>,
or mute the thread

**Comment by David-Estevez** [comment]
La electrónica ya está aquí, la he guardado en el armario, en la balda de GAME.

Nuria comentó que la mesa de air hockey también está ya pedida.

**Comment by David-Estevez** [comment]
Recibido paquete de RS, parece que ya está todo! :clap: :clap: :clap:
